apiVersion: apps/v1
kind: Deployment
metadata:
  name: firegr-deployment
  labels:
    app: firegr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: firegr
  template:
    metadata:
      labels:
        app: firegr
    spec:
      containers:
      - name: firegr
        image: trangta/firegr:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: firegr
spec:
  selector:
    app: firegr
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000